//! SQLite → Postgres data migration.
//!
//! Copies the user-authored contents of a local SQLite database file into a
//! Postgres instance under a freshly minted `db_id`, preserving every UUID so
//! cross-table references (wiki citations, chat citations, feed items,
//! report findings) survive unchanged.
//!
//! Derived data is deliberately NOT copied: chunk embeddings, tag centroids,
//! semantic edges and clusters are regenerated by the destination pipeline —
//! atoms land with `embedding_status = 'pending'` and the existing background
//! loops take over. Vectors from the source's embedding model would be
//! incompatible with the destination's provider and dimension anyway. Chunk
//! *text* is copied so keyword search works during the re-embedding backlog.
//!
//! Settings are not copied at all: on Postgres the `settings` table is
//! instance-global, so importing one database's overrides would reconfigure
//! every database on the server.
//!
//! Ordering matters for visibility: the `databases` registry row is inserted
//! only after every table has been copied and verified. Server background
//! loops discover databases through that row, so a half-copied database is
//! never visible to them — and cannot race the category-tag seeding in
//! `AtomicCore::open_postgres`. On failure every copied row is purged and the
//! error propagated.

mod tables;

use crate::db::Database;
use crate::error::AtomicCoreError;
use crate::storage::traits::DatabaseStore;
use crate::storage::PostgresStorage;
use std::path::Path;

/// Rows per read/insert batch. Large enough to amortize round-trips, small
/// enough that a batch of full-text atoms stays comfortably in memory.
const BATCH_SIZE: i64 = 500;

/// Source id-chunks per collision probe (`WHERE id = ANY($1)`).
const PROBE_CHUNK: usize = 5_000;

#[derive(Debug, Clone)]
pub struct MigrationOptions {
    /// Display name for the destination database.
    pub db_name: String,
    /// Count and validate without writing anything.
    pub dry_run: bool,
    /// Land all migrated feeds paused, so the destination doesn't start
    /// polling while the source instance may still be running.
    pub pause_feeds: bool,
}

#[derive(Debug, Clone, serde::Serialize)]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
pub struct TableCopyReport {
    pub table: String,
    /// Rows in the source table (before guards).
    pub source_rows: i64,
    /// Rows actually inserted. Less than `source_rows` when orphaned rows or
    /// conflicting feeds were skipped.
    pub copied_rows: i64,
}

#[derive(Debug, Clone, serde::Serialize)]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
pub struct MigrationReport {
    /// The destination db_id. `None` for dry runs.
    pub db_id: Option<String>,
    pub db_name: String,
    pub dry_run: bool,
    pub tables: Vec<TableCopyReport>,
    /// Feeds skipped because their URL already exists on the destination
    /// instance (feeds.url is unique across all databases there).
    pub skipped_feed_urls: Vec<String>,
    pub duration_ms: u64,
}

#[derive(Debug, Clone, serde::Serialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum MigrationEvent {
    Started {
        table_count: usize,
        total_rows: i64,
    },
    TableStarted {
        table: String,
        total_rows: i64,
    },
    TableProgress {
        table: String,
        copied_rows: i64,
        total_rows: i64,
    },
    TableCompleted {
        table: String,
        copied_rows: i64,
    },
}

/// Migrate a SQLite database file into Postgres under a new `db_id`.
///
/// `pg` may be scoped to any db_id — the migration mints its own. The source
/// file is upgraded in place to the current schema version first (old files
/// migrate transparently), then read via a read-only connection.
///
/// Fails fast (before writing) when any source primary key already exists on
/// the destination — that means this database was already migrated, and
/// proceeding would silently interleave rows into another database's data.
pub async fn migrate_sqlite_to_postgres<F, C>(
    source_db: &Path,
    pg: &PostgresStorage,
    options: MigrationOptions,
    on_event: F,
    is_cancelled: C,
) -> Result<MigrationReport, AtomicCoreError>
where
    F: Fn(MigrationEvent) + Send + Sync,
    C: Fn() -> bool + Send + Sync,
{
    let started = std::time::Instant::now();

    if !source_db.is_file() {
        return Err(AtomicCoreError::Validation(format!(
            "source database not found: {}",
            source_db.display()
        )));
    }

    // Upgrade the source schema in place, then reopen read-only for the copy.
    // `Database::open` also validates that this is a real Atomic database.
    let upgrade_path = source_db.to_path_buf();
    tokio::task::spawn_blocking(move || Database::open(&upgrade_path).map(drop))
        .await
        .map_err(|e| {
            AtomicCoreError::DatabaseOperation(format!("source open task failed: {e}"))
        })??;

    let mut reader = SqliteReader::open(source_db).await?;

    // ---- Pre-flight ----

    let source_counts = reader
        .call(|conn| {
            let mut counts = Vec::with_capacity(tables::TABLE_SPECS.len());
            for spec in tables::TABLE_SPECS {
                let n: i64 = conn.query_row(
                    &format!("SELECT COUNT(*) FROM {}", spec.source_table),
                    [],
                    |row| row.get(0),
                )?;
                counts.push((spec.table, n));
            }
            Ok(counts)
        })
        .await?;
    let total_rows: i64 = source_counts.iter().map(|(_, n)| n).sum();

    check_id_collisions(&mut reader, pg).await?;
    let skipped_feed_urls = find_conflicting_feed_urls(&mut reader, pg).await?;
    let skip_json = serde_json::to_string(&skipped_feed_urls)?;

    if options.dry_run {
        return Ok(MigrationReport {
            db_id: None,
            db_name: options.db_name,
            dry_run: true,
            tables: source_counts
                .iter()
                .map(|(table, n)| TableCopyReport {
                    table: table.to_string(),
                    source_rows: *n,
                    copied_rows: 0,
                })
                .collect(),
            skipped_feed_urls,
            duration_ms: started.elapsed().as_millis() as u64,
        });
    }

    // ---- Copy under a db_id that nothing can discover yet ----

    let db_id = uuid::Uuid::new_v4().to_string();
    on_event(MigrationEvent::Started {
        table_count: tables::TABLE_SPECS.len(),
        total_rows,
    });

    let copy_result = copy_all_tables(
        &mut reader,
        pg,
        &db_id,
        &options,
        &source_counts,
        &skip_json,
        &on_event,
        &is_cancelled,
    )
    .await;

    let table_reports = match copy_result {
        Ok(reports) => reports,
        Err(e) => {
            tracing::warn!(db_id = %db_id, error = %e, "migration failed; purging partial copy");
            if let Err(purge_err) = pg.purge_database_data(&db_id).await {
                tracing::error!(
                    db_id = %db_id,
                    error = %purge_err,
                    "failed to purge partially migrated database"
                );
            }
            return Err(e);
        }
    };

    // Commit marker: only now does the database become visible to
    // `list_databases()` and the server's background loops.
    let now = chrono::Utc::now().to_rfc3339();
    sqlx::query("INSERT INTO databases (id, name, is_default, created_at) VALUES ($1, $2, 0, $3)")
        .bind(&db_id)
        .bind(&options.db_name)
        .bind(&now)
        .execute(&pg.pool)
        .await
        .map_err(|e| {
            AtomicCoreError::DatabaseOperation(format!("failed to register database: {e}"))
        })?;

    tracing::info!(
        db_id = %db_id,
        name = %options.db_name,
        rows = table_reports.iter().map(|t| t.copied_rows).sum::<i64>(),
        "migration complete"
    );

    Ok(MigrationReport {
        db_id: Some(db_id),
        db_name: options.db_name,
        dry_run: false,
        tables: table_reports,
        skipped_feed_urls,
        duration_ms: started.elapsed().as_millis() as u64,
    })
}

/// Copy every table in FK order, then link tag parents, apply the feed pause,
/// and verify destination row counts.
#[allow(clippy::too_many_arguments)]
async fn copy_all_tables<F, C>(
    reader: &mut SqliteReader,
    pg: &PostgresStorage,
    db_id: &str,
    options: &MigrationOptions,
    source_counts: &[(&'static str, i64)],
    skip_json: &str,
    on_event: &F,
    is_cancelled: &C,
) -> Result<Vec<TableCopyReport>, AtomicCoreError>
where
    F: Fn(MigrationEvent) + Send + Sync,
    C: Fn() -> bool + Send + Sync,
{
    let mut reports = Vec::with_capacity(tables::TABLE_SPECS.len());

    for (spec, &(_, source_rows)) in tables::TABLE_SPECS.iter().zip(source_counts) {
        on_event(MigrationEvent::TableStarted {
            table: spec.table.to_string(),
            total_rows: source_rows,
        });

        let mut copied = 0i64;
        let mut last_rowid = 0i64;
        loop {
            if is_cancelled() {
                return Err(AtomicCoreError::Conflict("Migration cancelled".to_string()));
            }

            let skip = skip_json.to_string();
            let (cols, max_rowid, rows_read) = reader
                .call(move |conn| tables::read_batch(conn, spec, &skip, last_rowid, BATCH_SIZE))
                .await?;
            if rows_read == 0 {
                break;
            }

            tables::insert_batch(&pg.pool, db_id, spec, cols).await?;
            copied += rows_read as i64;
            last_rowid = max_rowid;
            on_event(MigrationEvent::TableProgress {
                table: spec.table.to_string(),
                copied_rows: copied,
                total_rows: source_rows,
            });
        }

        if spec.table == "tags" {
            link_tag_parents(reader, pg, db_id).await?;
        }

        on_event(MigrationEvent::TableCompleted {
            table: spec.table.to_string(),
            copied_rows: copied,
        });
        reports.push(TableCopyReport {
            table: spec.table.to_string(),
            source_rows,
            copied_rows: copied,
        });
    }

    if options.pause_feeds {
        sqlx::query("UPDATE feeds SET is_paused = 1 WHERE db_id = $1")
            .bind(db_id)
            .execute(&pg.pool)
            .await
            .map_err(|e| {
                AtomicCoreError::DatabaseOperation(format!("failed to pause feeds: {e}"))
            })?;
    }

    verify_copy(pg, db_id, &reports).await?;
    Ok(reports)
}

/// Second tag pass: wire up parent_id now that every tag row exists. Doing
/// this after the fact avoids topological insert ordering for the hierarchy.
async fn link_tag_parents(
    reader: &mut SqliteReader,
    pg: &PostgresStorage,
    db_id: &str,
) -> Result<(), AtomicCoreError> {
    let pairs: Vec<(String, String)> = reader
        .call(|conn| {
            let mut stmt = conn.prepare(
                "SELECT id, parent_id FROM tags \
                 WHERE parent_id IS NOT NULL AND parent_id IN (SELECT id FROM tags)",
            )?;
            let rows = stmt
                .query_map([], |row| Ok((row.get(0)?, row.get(1)?)))?
                .collect::<Result<Vec<_>, _>>()?;
            Ok(rows)
        })
        .await?;

    for chunk in pairs.chunks(BATCH_SIZE as usize) {
        let (ids, parents): (Vec<String>, Vec<String>) = chunk.iter().cloned().unzip();
        sqlx::query(
            "UPDATE tags SET parent_id = u.parent_id \
             FROM (SELECT UNNEST($1::text[]) AS id, UNNEST($2::text[]) AS parent_id) u \
             WHERE tags.id = u.id AND tags.db_id = $3",
        )
        .bind(&ids)
        .bind(&parents)
        .bind(db_id)
        .execute(&pg.pool)
        .await
        .map_err(|e| {
            AtomicCoreError::DatabaseOperation(format!("failed to link tag parents: {e}"))
        })?;
    }
    Ok(())
}

/// Abort when any source primary key already exists on the destination —
/// in any database, since primary keys there are global and `db_id` is only
/// a filter column. A hit means this source was already migrated; inserting
/// anyway (or skipping conflicts) would silently attach rows to another
/// database's data.
async fn check_id_collisions(
    reader: &mut SqliteReader,
    pg: &PostgresStorage,
) -> Result<(), AtomicCoreError> {
    // Root entity tables: every other table's keys derive from these, so
    // probing them is sufficient to detect a re-migration.
    const ROOTS: &[&str] = &[
        "atoms",
        "tags",
        "wiki_articles",
        "conversations",
        "feeds",
        "reports",
    ];

    for table in ROOTS {
        let table = *table;
        let ids: Vec<String> = reader
            .call(move |conn| {
                let mut stmt = conn.prepare(&format!("SELECT id FROM {table}"))?;
                let rows = stmt
                    .query_map([], |row| row.get(0))?
                    .collect::<Result<Vec<_>, _>>()?;
                Ok(rows)
            })
            .await?;

        let mut collisions = 0usize;
        let mut examples: Vec<String> = Vec::new();
        for chunk in ids.chunks(PROBE_CHUNK) {
            let hits: Vec<String> =
                sqlx::query_scalar(&format!("SELECT id FROM {table} WHERE id = ANY($1)"))
                    .bind(chunk)
                    .fetch_all(&pg.pool)
                    .await
                    .map_err(|e| {
                        AtomicCoreError::DatabaseOperation(format!(
                            "collision check on {table} failed: {e}"
                        ))
                    })?;
            for hit in hits {
                if examples.len() < 3 {
                    examples.push(hit);
                }
                collisions += 1;
            }
        }

        if collisions > 0 {
            return Err(AtomicCoreError::Conflict(format!(
                "{collisions} {table} row(s) from this database already exist on the \
                 destination (e.g. {examples:?}). This database appears to have been \
                 migrated before — delete the previous copy first, then retry."
            )));
        }
    }
    Ok(())
}

/// Feed URLs that already exist on the destination under any database.
/// `feeds.url` is globally unique there, so these feeds (and their
/// feed_tags/feed_items) are skipped rather than failing the migration.
async fn find_conflicting_feed_urls(
    reader: &mut SqliteReader,
    pg: &PostgresStorage,
) -> Result<Vec<String>, AtomicCoreError> {
    let urls: Vec<String> = reader
        .call(|conn| {
            let mut stmt = conn.prepare("SELECT url FROM feeds")?;
            let rows = stmt
                .query_map([], |row| row.get(0))?
                .collect::<Result<Vec<_>, _>>()?;
            Ok(rows)
        })
        .await?;

    let mut conflicting = Vec::new();
    for chunk in urls.chunks(PROBE_CHUNK) {
        let hits: Vec<String> = sqlx::query_scalar("SELECT url FROM feeds WHERE url = ANY($1)")
            .bind(chunk)
            .fetch_all(&pg.pool)
            .await
            .map_err(|e| {
                AtomicCoreError::DatabaseOperation(format!("feed URL check failed: {e}"))
            })?;
        conflicting.extend(hits);
    }
    if !conflicting.is_empty() {
        tracing::warn!(
            urls = ?conflicting,
            "skipping feeds whose URL already exists on the destination"
        );
    }
    Ok(conflicting)
}

/// Belt-and-suspenders: destination row counts must match what we copied.
async fn verify_copy(
    pg: &PostgresStorage,
    db_id: &str,
    reports: &[TableCopyReport],
) -> Result<(), AtomicCoreError> {
    for report in reports {
        let count: i64 = sqlx::query_scalar(&format!(
            "SELECT COUNT(*) FROM {} WHERE db_id = $1",
            report.table
        ))
        .bind(db_id)
        .fetch_one(&pg.pool)
        .await
        .map_err(|e| {
            AtomicCoreError::DatabaseOperation(format!(
                "verification count on {} failed: {e}",
                report.table
            ))
        })?;
        if count != report.copied_rows {
            return Err(AtomicCoreError::DatabaseOperation(format!(
                "verification failed for {}: copied {} rows but destination has {}",
                report.table, report.copied_rows, count
            )));
        }
    }
    Ok(())
}

/// Count the atoms in a SQLite database file without upgrading or copying
/// anything — used by upload admission to enforce an atom budget before an
/// import starts. Errors with `Validation` when the file has no `atoms`
/// table (a valid SQLite database that is not an Atomic knowledge base).
pub async fn count_source_atoms(path: &Path) -> Result<i64, AtomicCoreError> {
    let path = path.to_path_buf();
    tokio::task::spawn_blocking(move || {
        let conn = rusqlite::Connection::open_with_flags(
            &path,
            rusqlite::OpenFlags::SQLITE_OPEN_READ_ONLY,
        )?;
        conn.query_row("SELECT COUNT(*) FROM atoms", [], |row| row.get(0))
            .map_err(|_| {
                AtomicCoreError::Validation(
                    "Upload is not an Atomic database (no atoms table)".to_string(),
                )
            })
    })
    .await
    .map_err(|e| AtomicCoreError::DatabaseOperation(format!("atom count task failed: {e}")))?
}

/// A read-only SQLite connection shuttled in and out of `spawn_blocking` so
/// reads never block the async runtime. `Connection` is `Send` but not
/// `Sync`, hence the move-and-return dance.
struct SqliteReader {
    conn: Option<rusqlite::Connection>,
}

impl SqliteReader {
    async fn open(path: &Path) -> Result<Self, AtomicCoreError> {
        let path = path.to_path_buf();
        let conn = tokio::task::spawn_blocking(move || {
            rusqlite::Connection::open_with_flags(
                &path,
                rusqlite::OpenFlags::SQLITE_OPEN_READ_ONLY
                    | rusqlite::OpenFlags::SQLITE_OPEN_NO_MUTEX,
            )
        })
        .await
        .map_err(|e| {
            AtomicCoreError::DatabaseOperation(format!("sqlite open task failed: {e}"))
        })??;
        Ok(Self { conn: Some(conn) })
    }

    async fn call<T, F>(&mut self, f: F) -> Result<T, AtomicCoreError>
    where
        T: Send + 'static,
        F: FnOnce(&rusqlite::Connection) -> rusqlite::Result<T> + Send + 'static,
    {
        let conn = self
            .conn
            .take()
            .expect("SqliteReader connection already in use");
        let (conn, result) = tokio::task::spawn_blocking(move || {
            let result = f(&conn);
            (conn, result)
        })
        .await
        .map_err(|e| AtomicCoreError::DatabaseOperation(format!("sqlite read task failed: {e}")))?;
        self.conn = Some(conn);
        result.map_err(AtomicCoreError::from)
    }
}
