import { useEffect, useMemo, useState } from 'react';
import { BookOpen, Search, Waypoints, X } from 'lucide-react';
import { isDemoInstance, demoSignupUrl } from '../../lib/transport';
import { useWikiStore } from '../../stores/wiki';
import { useUIStore } from '../../stores/ui';

const DISMISS_KEY = 'atomic-demo-intro-dismissed';
/** DemoBanner's "What is this?" fires this to re-open a dismissed card. */
export const DEMO_INTRO_REOPEN_EVENT = 'atomic-demo-intro-reopen';

/**
 * Orientation card at the top of the demo instance's dashboard. A cold
 * visitor (e.g. from an HN comment) lands on a dense, populated product UI
 * with no explanation of what the product is or where the content came
 * from — this card is that explanation, plus three deep links that each
 * land on a "how did it do that" moment in one click. Deliberately an
 * inline card, not a modal: it must share the first glance with the
 * content it explains, not block it.
 *
 * Demo-gated and dismissible (localStorage); never renders for real
 * tenants or self-hosted.
 */
export function DemoIntroCard() {
  const [dismissed, setDismissed] = useState(
    () => localStorage.getItem(DISMISS_KEY) === 'true'
  );
  const articles = useWikiStore(s => s.articles);
  const openWikiReader = useUIStore(s => s.openWikiReader);
  const setViewMode = useUIStore(s => s.setViewMode);
  const openSearchPalette = useUIStore(s => s.openSearchPalette);

  useEffect(() => {
    const reopen = () => {
      localStorage.removeItem(DISMISS_KEY);
      setDismissed(false);
    };
    window.addEventListener(DEMO_INTRO_REOPEN_EVENT, reopen);
    return () => window.removeEventListener(DEMO_INTRO_REOPEN_EVENT, reopen);
  }, []);

  // The showcase wiki: prefer the LLM article by name, else the one built
  // from the most atoms. Falls back to hiding the row if no wikis loaded.
  const showcase = useMemo(() => {
    if (articles.length === 0) return null;
    return (
      articles.find(a => /large language/i.test(a.tag_name)) ??
      [...articles].sort((a, b) => b.atom_count - a.atom_count)[0]
    );
  }, [articles]);

  if (!isDemoInstance() || dismissed) return null;

  const dismiss = () => {
    localStorage.setItem(DISMISS_KEY, 'true');
    setDismissed(true);
  };

  const tryRow =
    'flex items-center gap-2 text-sm text-[var(--color-text-secondary)] hover:text-[var(--color-text-primary)] transition-colors group';
  const tryIcon =
    'w-4 h-4 text-[var(--color-accent-light)] flex-shrink-0 group-hover:scale-110 transition-transform';

  return (
    <div className="relative mb-10 rounded-xl border border-[var(--color-border)] bg-[var(--color-bg-secondary)] p-5 md:p-6">
      <button
        onClick={dismiss}
        title="Dismiss"
        className="absolute top-3 right-3 text-[var(--color-text-tertiary)] hover:text-[var(--color-text-primary)] transition-colors"
      >
        <X className="w-4 h-4" strokeWidth={2} />
      </button>

      <p className="text-sm md:text-[15px] leading-relaxed text-[var(--color-text-secondary)] pr-6">
        This is a live demo of{' '}
        <span className="font-semibold text-[var(--color-text-primary)]">Atomic</span>, an
        open-source knowledge base. It's seeded with ~130 AI/ML papers — everything else
        here (the tags, the graph, the wikis, the weekly digest below) was generated by
        Atomic itself. It's read-only.
      </p>

      <div className="mt-4 flex flex-col gap-2.5 sm:flex-row sm:items-center sm:gap-6">
        {showcase && (
          <button
            className={tryRow}
            onClick={() => openWikiReader(showcase.tag_id, showcase.tag_name)}
          >
            <BookOpen className={tryIcon} strokeWidth={2} />
            <span>
              A wiki it wrote{' '}
              <span className="text-[var(--color-text-tertiary)]">(with citations)</span>
            </span>
          </button>
        )}
        <button className={tryRow} onClick={() => setViewMode('canvas')}>
          <Waypoints className={tryIcon} strokeWidth={2} />
          <span>
            The canvas{' '}
            <span className="text-[var(--color-text-tertiary)]">— semantic clusters</span>
          </span>
        </button>
        <button className={tryRow} onClick={() => openSearchPalette()}>
          <Search className={tryIcon} strokeWidth={2} />
          <span>
            Search{' '}
            <span className="text-[var(--color-text-tertiary)]">— keyword + semantic</span>
          </span>
        </button>
      </div>

      <div className="mt-4 pt-3 border-t border-[var(--color-border)] flex items-center gap-4 text-sm">
        <a
          href="https://github.com/kenforthewin/atomic"
          target="_blank"
          rel="noopener noreferrer"
          className="text-[var(--color-text-tertiary)] hover:text-[var(--color-text-primary)] transition-colors"
        >
          GitHub ↗
        </a>
        <a
          href={demoSignupUrl()}
          className="font-medium text-[var(--color-accent-light)] hover:underline"
        >
          Get your own →
        </a>
      </div>
    </div>
  );
}
